name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Make Dockerfile
        run: |
          echo "FROM debian:buster-20201012
          RUN apt-get update && apt-cache policy php && apt-get install -y php" > Dockerfile

      - name: Build docker
        run: docker build --no-cache -t php-test .

      - name: Run tests
        run: docker run --rm trw-test make test
